name: Pull Request Check

run-name: ${{ github.repository }} is evaluating pull request
#on: [pull_request]

on:
  pull_request:

  # REMOVEME
  workflow_dispatch:

permissions:
  # Required to upload SARIF file to CodeQL. See: https://github.com/github/codeql-action/issues/2117
  actions: read
  # Require writing security events to upload SARIF file to security tab
  # As described at https://github.com/github/codeql-action?tab=readme-ov-file#workflow-permissions
  security-events: write
  # to fetch code (actions/checkout)
  contents: read
  # ???
  packages: write
  attestations: write
  id-token: write

jobs:
  rust-pull-request-check:
    # just reuse a relevant workflow from the dedicated repo https://github.com/swiyu-admin-ch/github-actions-workflows
    #uses: swiyu-admin-ch/github-actions-workflows/.github/workflows/rust-pull-request-check.yml@main
    uses: swiyu-admin-ch/github-actions-workflows/.github/workflows/rust-pull-request-check.yml@feat/EIDOMNI-262-rust-pull-request-check
      #with:
      # Whether to build artifacts for normal development and debugging (default: true)
      #debug: true
      # Whether to also build artifacts in release mode, with optimizations
    #release: false
